input_aggregation_object = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
key_hash = ""
proof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
public_inputs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
verification_key = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]

[[borders]]

[borders.latitude]
fraction = "82"
integer = ""

[borders.longitude]
fraction = "66"
integer = ""

[[borders]]

[borders.latitude]
fraction = "79"
integer = ""

[borders.longitude]
fraction = "61"
integer = ""

[[borders]]

[borders.latitude]
fraction = "99"
integer = ""

[borders.longitude]
fraction = "50"
integer = ""

[[borders]]

[borders.latitude]
fraction = "122"
integer = ""

[borders.longitude]
fraction = "71"
integer = ""

[location.latitude]
fraction = "99"
integer = ""

[location.longitude]
fraction = "66"
integer = ""
